// ─── Complete ICONIQ Portfolio (All Funds Since Inception) ─────────────────
export const ICONIQ_PORTFOLIO = [
  '1Password','AcuityMD','Adyen','Age of Learning','Airbnb','Airtable','Ajaib',
  'Alibaba','Alteryx','Altruist','Anthropic','Apprentice','Articulate','Aurora Solar',
  'Automattic','Axonius','BambooHR','Benchling','BetterUp','Bill.com','Blackline Systems',
  'Braintrust','Braze','Calendly','Campaign Monitor','Canva','CaptivateIQ','Causaly',
  'Chime','Clara','Coast','Collibra','Conexiom','Coupa','CrowdStrike','CyberGRX',
  'Databricks','Datadog','Dataiku','dbt','DeepL','Devoted Health','DexCare','Dialpad',
  'DocuSign','Drata','DX','ElevenLabs','Enfusion','Epic Games','EvolutionIQ','EzCater',
  'Fastly','Fetch Rewards','Figma','Fireblocks','Fivetran','Flipkart','FloQast',
  'Freewill','FTX Trading','Gem','GitLab','Glean','GoFundMe','GoodRx','GreenSky',
  'Grotto','Groww','Guild','HashiCorp','HeadSpin','HighRadius','Highspot','Hightouch',
  'Hippo','The Honest Company','Houzz','IEX','Incident IQ','Intercom','InVision',
  'Komodo Health','Lead Bank','Legora','Loom','Lucid','Marqeta','Miro','Monte Carlo',
  'Monzo','Motorway','Moveworks','Nayya','Netskope','Nevis','NinjaOne','Notable',
  'OpenAI','OpenEvidence','Oura','Outtake','Pigment','Procore','Ramp','Rain',
  'Restaurant365','Revolut','Rillet','Robinhood','ServiceTitan','Sierra','Snowflake',
  'Sprinklr','ST Labs','Stripe','Swap','Tennr','Tiny Fish','Truckstop','UnifyApps',
  'VIC.AI','Virtru','Wealthsimple','Whirl AI','Writer','Zinier',
]

// ─── ISP VII Full Portfolio Valuations (as of December 31, 2025) ───────────
export const ISP7_PORTFOLIO = [
  // ── Fully Realized ──────────────────────────────────────────────────────
  {
    company: 'DX', date: '2024-05-13', status: 'Acquired by Atlassian',
    realized: true, fund_pct: 0.8, invested_m: 43.5, realized_m: 141.9,
    fmv_m: 8.3, total_value_m: 150.1, gross_moic: 3.4, net_moic: 3.0,
    sector: 'Developer Experience', hq: null,
    description: 'Developer experience platform acquired by Atlassian for $1.0B (November 2025). One of the highest gross IRR exits in ISP VII at 176.7%.',
    developments: ['Acquired by Atlassian (NASDAQ: TEAM) for $1.0B in November 2025', 'Highest IRR exit in ISP VII: 176.7% gross'],
  },
  // ── Partially Realized ──────────────────────────────────────────────────
  {
    company: 'Adyen', date: '2023-08-17', status: 'Public (AMS: ADYEN)',
    realized: false, partial: true, fund_pct: 3.7, invested_m: 214.2,
    realized_m: 111.0, fmv_m: 172.4, total_value_m: 283.3, gross_moic: 1.3, net_moic: 1.2,
    sector: 'Payments / Fintech', hq: 'Amsterdam, Netherlands',
    description: 'Global payments platform. Public on Euronext Amsterdam.',
    developments: ['Stock at €1,375/share on 12/31/25, down ~12% from €1,558 on 6/30/25', 'Partial realization of $111M in 2H\'25'],
  },
  {
    company: 'CCC Intelligent Solutions', date: '2024-02-01', status: 'Private (acq. EvolutionIQ)',
    realized: false, partial: true, fund_pct: 0.4, invested_m: 21.9,
    realized_m: 18.8, fmv_m: 9.3, total_value_m: 28.1, gross_moic: 1.3, net_moic: 1.1,
    sector: 'Insurance AI', hq: null,
    description: 'AI-powered insurance and automotive claims platform following acquisition of EvolutionIQ.',
    developments: ['Partial realization of $18.8M'],
  },
  {
    company: 'Figma', date: '2024-04-08', status: 'Public (NYSE: FIG)',
    realized: false, partial: true, fund_pct: 2.3, invested_m: 130.6,
    realized_m: 0.3, fmv_m: 216.5, total_value_m: 216.8, gross_moic: 1.7, net_moic: 1.4,
    sector: 'Design / Dev Tools', hq: 'San Francisco, CA',
    description: 'Collaborative design and development platform. IPO July 31, 2025 at $33/share.',
    developments: ['IPO on NYSE: FIG at $33.00/share (July 31, 2025)', 'Stock at $37.37 on 12/31/25 (+13% from IPO)', 'Agreement to acquire Weavy for media generation capability (October 2025)'],
  },
  // ── Unrealized (Active) ─────────────────────────────────────────────────
  {
    company: 'AcuityMD', date: '2024-04-12', status: 'Private',
    realized: false, fund_pct: 0.9, invested_m: 49.5, fmv_m: 76.9,
    total_value_m: 76.9, gross_moic: 1.6, net_moic: 1.4,
    sector: 'MedTech / Healthcare', hq: null,
    description: 'Vertical platform for MedTech sales reps to identify, target, and prioritize prospects using claims data and procedure-level insights.',
    developments: ['Launched MedTech AI tools to accelerate commercial growth (October 2025)', 'Follow-on investment of $7.5M in 2H\'25'],
  },
  {
    company: 'Altruist', date: '2024-01-31', status: 'Private',
    realized: false, fund_pct: 1.8, invested_m: 105.0, fmv_m: 105.0,
    total_value_m: 105.0, gross_moic: 1.0, net_moic: 0.9,
    sector: 'WealthTech', hq: null,
    description: 'Modern custodian and brokerage platform for independent RIAs, offering low-cost digital infrastructure for wealth managers.',
    developments: ['Launched Hazel, first AI platform for wealth managers unifying real-time custodial data with CRM, emails, and meeting notes (September 2025)'],
  },
  {
    company: 'Anthropic', date: '2025-08-18', status: 'Private',
    realized: false, fund_pct: 10.4, invested_m: 600.0, fmv_m: 1147.5,
    total_value_m: 1147.5, gross_moic: 1.9, net_moic: 1.7,
    sector: 'AI / Foundation Models', hq: 'San Francisco, CA',
    isp7_new: true,
    description: 'Leading AI model company and research lab behind the Claude family of large language models. Focused on building reliable, interpretable, and safe AI systems. Strong developer trust and mindshare, with Claude increasingly adopted across enterprise and API-driven workloads. ICONIQ led Anthropic\'s Series F. Co-led Series G in February 2026. Total FMV across all ICONIQ funds: $4.9B.',
    developments: ['Named to Forbes Cloud 100', 'Series F financing announced (September 2025)', 'Launched Claude Opus 4.5 (November 2025), Sonnet 4.5 (September 2025), Haiku 4.5 (October 2025)', 'Entered agreement to acquire Bun to accelerate Claude Code (December 2025)', 'Co-led Series G in February 2026'],
  },
  {
    company: 'Assured', date: '2024-10-11', status: 'Private',
    realized: false, fund_pct: 0.5, invested_m: 31.3, fmv_m: 31.3,
    total_value_m: 31.3, gross_moic: 1.0, net_moic: 0.9,
    sector: 'Insurtech', hq: null,
    description: 'Digital insurance platform.',
    developments: [],
  },
  {
    company: 'Atomix Data', date: '2025-07-10', status: 'Private',
    realized: false, fund_pct: 0.1, invested_m: 7.7, fmv_m: 7.7,
    total_value_m: 7.7, gross_moic: 1.0, net_moic: 0.9,
    sector: 'Data Infrastructure', hq: 'New York, NY',
    isp7_new: true,
    description: 'Next-generation data infrastructure company building a streamlined distributed database designed to replace Redis. Offers improved durability, scalability, and transactional guarantees. ICONIQ led seed round.',
    developments: [],
  },
  {
    company: 'BambooHR', date: '2024-01-08', status: 'Private',
    realized: false, fund_pct: 3.2, invested_m: 182.2, fmv_m: 195.1,
    total_value_m: 195.2, gross_moic: 1.1, net_moic: 0.9,
    sector: 'HR Tech', hq: null,
    description: 'Leading HR software platform for small and medium businesses, offering HRIS, payroll, benefits, and performance management.',
    developments: ['New CMO: Adam Christensen (former CMO of Notified, November 2025)', 'Partnership with EasyLlama for compliance training for SMBs', 'New Xero Payroll integrations in UK, Australia, New Zealand (December 2025)'],
  },
  {
    company: 'Braintrust', date: '2025-12-02', status: 'Private',
    realized: false, fund_pct: 0.7, invested_m: 41.4, fmv_m: 41.1,
    total_value_m: 41.1, gross_moic: 1.0, net_moic: 0.9,
    sector: 'AI Infrastructure', hq: 'San Francisco, CA',
    isp7_new: true,
    description: 'End-to-end AI infrastructure platform providing evaluation, testing, and observability tools for LLM-powered applications and agents. Increasingly the platform of choice for technically sophisticated AI builders and enterprises. ICONIQ led Series B.',
    developments: ['Announced Loop AI assistant for plain-English data querying (November 2025)', 'Launched MCP server for AI coding tools (September 2025)'],
  },
  {
    company: 'Canva', date: '2023-08-07', status: 'Private',
    realized: false, fund_pct: 1.7, invested_m: 100.0, fmv_m: 130.0,
    total_value_m: 130.0, gross_moic: 1.3, net_moic: 1.1,
    sector: 'Creative / Design', hq: 'Sydney, Australia',
    description: 'Visual communication and design platform used by 200M+ people. Expanding into AI-powered creative workflows.',
    developments: ['Named to Forbes Cloud 100', 'Launched Creative Operating System, AI-powered foundation across Visual Suite (October 2025)', 'Launched Affinity (free) for professional creativity (October 2025)', 'Launched Canva Business subscription (October 2025)'],
  },
  {
    company: 'Causaly', date: '2023-06-21', status: 'Private',
    realized: false, fund_pct: 0.7, invested_m: 40.0, fmv_m: 40.0,
    total_value_m: 40.0, gross_moic: 1.0, net_moic: 0.9,
    sector: 'Life Sciences AI', hq: null,
    description: 'AI-powered biomedical research platform enabling rapid drug discovery through causal relationship mapping across scientific literature.',
    developments: ['Introduced Agentic Research for drug discovery automation (September 2025)'],
  },
  {
    company: 'ClickHouse', date: '2024-10-21', status: 'Private',
    realized: false, fund_pct: 0.1, invested_m: 5.0, fmv_m: 29.5,
    total_value_m: 29.5, gross_moic: 5.9, net_moic: 5.1,
    sector: 'Data Infrastructure', hq: null,
    description: 'Open-source columnar database for real-time analytics. Exceptional performance on high-throughput analytical workloads. Highest unrealized MOIC in active ISP VII portfolio at 5.9x gross.',
    developments: ['Announced Series C extension (October 2025)', 'New CRO: Kevin Egan (former Head of Global Enterprise Sales, Atlassian, July 2025)'],
  },
  {
    company: 'Coast', date: '2024-06-14', status: 'Private',
    realized: false, fund_pct: 0.5, invested_m: 30.0, fmv_m: 30.0,
    total_value_m: 30.0, gross_moic: 1.0, net_moic: 0.9,
    sector: 'Fintech / Fleet', hq: null,
    description: 'Modern fleet card and expense management platform for businesses managing vehicle fleets and field operations.',
    developments: ['Announced Coast for Private Equity — expense management for PE portfolio companies'],
  },
  {
    company: 'Databricks', date: '2024-12-17', status: 'Private',
    realized: false, fund_pct: 3.7, invested_m: 210.0, fmv_m: 423.5,
    total_value_m: 423.5, gross_moic: 2.0, net_moic: 1.8,
    sector: 'Data / AI Platform', hq: 'San Francisco, CA',
    description: 'Comprehensive data and AI platform unifying data engineering, analytics, and ML. The dominant platform for enterprise data lakehouse architecture.',
    developments: ['Named to Forbes Cloud 100', 'Announced Series K (August 2025) and Series L (December 2025)', 'Strategic partnership with OpenAI for Databricks Agent Bricks', 'Follow-on investment of $10M in 2H\'25'],
  },
  {
    company: 'DeepL', date: '2024-06-20', status: 'Private',
    realized: false, fund_pct: 0.9, invested_m: 53.8, fmv_m: 68.9,
    total_value_m: 68.9, gross_moic: 1.3, net_moic: 1.1,
    sector: 'Language AI', hq: 'Cologne, Germany',
    description: 'Neural machine translation and language AI platform known for superior translation quality versus Google Translate, with strong enterprise traction.',
    developments: ['Named to Forbes Cloud 100', 'Launched DeepL Agent, autonomous AI coworker (November 2025)'],
  },
  {
    company: 'DriveCentric', date: '2024-08-15', status: 'Private',
    realized: false, fund_pct: 3.2, invested_m: 183.7, fmv_m: 222.0,
    total_value_m: 244.2, gross_moic: 1.3, net_moic: 1.2,
    sector: 'Automotive AI / CRM', hq: null,
    description: 'AI-powered CRM and customer engagement platform purpose-built for automotive dealerships.',
    developments: ['Partnership with automotiveMastermind (September 2025)', 'Partnership with TradePending (October 2025)'],
  },
  {
    company: 'ElevenLabs', date: '2024-11-08', status: 'Private',
    realized: false, fund_pct: 2.2, invested_m: 124.0, fmv_m: 324.3,
    total_value_m: 324.3, gross_moic: 2.6, net_moic: 2.3,
    sector: 'AI Audio / Voice', hq: 'New York, NY',
    description: 'AI audio research and deployment platform enabling high-quality voice cloning, text-to-speech, and audio generation. Rapid enterprise adoption in media, publishing, and developer tooling.',
    developments: ['Named to Forbes Cloud 100', 'Launched Music API for licensed music generation and expressive TTS (August 2025)', 'Follow-on investment of $44M in 2H\'25'],
  },
  {
    company: 'FloQast', date: '2023-05-30', status: 'Private',
    realized: false, fund_pct: 3.3, invested_m: 190.9, fmv_m: 213.6,
    total_value_m: 213.6, gross_moic: 1.1, net_moic: 1.0,
    sector: 'Accounting Tech', hq: null,
    description: 'Leader in close management and accounting workflow software for mid-market and enterprise finance teams.',
    developments: ['Launched AI Agent Builder (September 2025)', 'Partnership with Trovata for bank transaction data automation (October 2025)', 'Strategic alliance with Deloitte Australia (August 2025)', 'Follow-on of $1.9M in 2H\'25'],
  },
  {
    company: 'Glean', date: '2024-02-01', status: 'Private',
    realized: false, fund_pct: 0.6, invested_m: 32.1, fmv_m: 75.8,
    total_value_m: 75.8, gross_moic: 2.4, net_moic: 2.1,
    sector: 'Enterprise AI / Search', hq: 'Palo Alto, CA',
    description: 'Enterprise AI search platform indexing all company data — Slack, email, Drive, wikis, internal tools — with strong retrieval-augmented generation. Used by 1,000+ enterprises.',
    developments: ['Named to Forbes Cloud 100', 'Surpassed $200M ARR, doubling revenue in nine months (December 2025)'],
  },
  {
    company: 'Grotto', date: '2025-06-23', status: 'Private',
    realized: false, fund_pct: 0.1, invested_m: 6.4, fmv_m: 6.4,
    total_value_m: 6.4, gross_moic: 1.0, net_moic: 0.9,
    sector: 'PropTech AI', hq: null,
    description: 'AI-native platform for intelligent leasing and renewals in multifamily property management.',
    developments: ['Follow-on investment of $3.4M in 2H\'25'],
  },
  {
    company: 'Groww', date: '2025-06-09', status: 'Public (NSE/BSE: GROWW)',
    realized: false, fund_pct: 2.6, invested_m: 151.7, fmv_m: 234.2,
    total_value_m: 234.2, gross_moic: 1.5, net_moic: 1.3,
    sector: 'Fintech / Retail Brokerage', hq: 'Bengaluru, India',
    description: 'India\'s leading low-cost digital retail brokerage platform, serving tens of millions of first-time investors.',
    developments: ['IPO on NSE/BSE, raised ~₹6.6B (~$750M) in net proceeds (November 2025)', 'Secured OBPP license from SEBI (December 2025)', 'Stock up 56% from IPO listing price as of 12/31/2025', 'Follow-on of $36.4M in 2H\'25'],
  },
  {
    company: 'Incident IQ', date: '2024-02-23', status: 'Private',
    realized: false, fund_pct: 0.5, invested_m: 30.0, fmv_m: 36.0,
    total_value_m: 36.0, gross_moic: 1.2, net_moic: 1.0,
    sector: 'EdTech / IT Management', hq: null,
    description: 'Asset management and service management platform built specifically for K-12 school districts.',
    developments: [],
  },
  {
    company: 'Lead Bank', date: '2025-08-19', status: 'Private',
    realized: false, fund_pct: 0.6, invested_m: 35.0, fmv_m: 35.0,
    total_value_m: 35.0, gross_moic: 1.0, net_moic: 0.9,
    sector: 'Fintech / BaaS', hq: 'Kansas City, MO',
    isp7_new: true,
    description: 'Vertically integrated Banking-as-a-Service platform enabling FinTechs to embed financial services including card issuance, lending, deposits, payments, and stablecoin infrastructure. Fully chartered and regulated bank. ICONIQ invested via secondary transaction.',
    developments: ['Announced Series B financing (September 2025)', 'Entered agreement to acquire Loop Crypto (December 2025)'],
  },
  {
    company: 'Legora', date: '2025-05-19', status: 'Private',
    realized: false, fund_pct: 1.2, invested_m: 67.0, fmv_m: 115.7,
    total_value_m: 115.7, gross_moic: 1.7, net_moic: 1.5,
    sector: 'Legal AI', hq: null,
    description: 'Collaborative AI platform for legal professionals enabling AI-assisted drafting, research, and matter management across law firms and in-house teams.',
    developments: ['Announced Series C financing (October 2025)', 'Launched Legora Portal for law firm / in-house team collaboration (November 2025)', 'Global partnership with White & Case LLP (December 2025)', 'Follow-on of $32M in 2H\'25'],
  },
  {
    company: 'Monzo', date: '2024-04-30', status: 'Private',
    realized: false, fund_pct: 3.0, invested_m: 175.0, fmv_m: 262.4,
    total_value_m: 262.4, gross_moic: 1.5, net_moic: 1.3,
    sector: 'Neobanking', hq: 'London, UK',
    description: 'UK-based digital bank with 10M+ customers. Expanding into business banking and European markets.',
    developments: ['New CEO: Diana Layfield (former Google, joining February 2026, succeeding TS Anil)', 'Agreement to acquire Habito (UK digital mortgage broker, December 2025)', 'Secured full banking license from European Central Bank and Central Bank of Ireland (December 2025)'],
  },
  {
    company: 'Nevis', date: '2025-10-29', status: 'Private',
    realized: false, fund_pct: 0.1, invested_m: 5.0, fmv_m: 5.0,
    total_value_m: 5.0, gross_moic: 1.0, net_moic: 0.9,
    sector: 'WealthTech AI', hq: 'London, UK',
    isp7_new: true,
    description: 'AI-native operating system for wealth managers, RIAs, and family offices. Unifies onboarding, CRM, service workflows, and analytics. Uses LLMs to surface insights and automate manual workflows. ICONIQ invested in Series A.',
    developments: ['Announced Series A financing (December 2025)'],
  },
  {
    company: 'Omni', date: '2025-03-03', status: 'Private',
    realized: false, fund_pct: 0.5, invested_m: 31.0, fmv_m: 31.0,
    total_value_m: 31.0, gross_moic: 1.0, net_moic: 0.9,
    sector: 'Analytics / Data', hq: null,
    description: 'Unified analytics platform for business intelligence and embedded analytics.',
    developments: ['Agreement to acquire Explo for unified analytics platform (October 2025)'],
  },
  {
    company: 'OpenAI', date: '2025-10-03', status: 'Private',
    realized: false, fund_pct: 1.6, invested_m: 90.1, fmv_m: 90.1,
    total_value_m: 90.1, gross_moic: 1.0, net_moic: 0.9,
    sector: 'AI / Foundation Models', hq: 'San Francisco, CA',
    isp7_new: true,
    description: 'Frontier AI lab focused on AI research and language models. ChatGPT has over 1 billion monthly active users. ICONIQ invested via highly competitive secondary transaction.',
    developments: ['Acquired Statsig (all-equity, December 2025, $1.2B)', 'Strategic partnership with NVIDIA (September 2025)'],
  },
  {
    company: 'OpenAI (acq. Statsig)', date: '2025-03-19', status: 'Private (acq. by OpenAI)',
    realized: false, fund_pct: 1.4, invested_m: 80.0, fmv_m: 112.1,
    total_value_m: 112.1, gross_moic: 1.4, net_moic: 1.2,
    sector: 'Developer Tools / Analytics', hq: null,
    description: 'Product analytics and feature flagging platform (formerly Statsig), acquired by OpenAI for $1.2B in December 2025.',
    developments: ['Acquired by OpenAI for $1.2B (December 2025)'],
  },
  {
    company: 'OpenEvidence', date: '2025-08-08', status: 'Private',
    realized: false, fund_pct: 0.9, invested_m: 50.0, fmv_m: 163.8,
    total_value_m: 163.8, gross_moic: 3.3, net_moic: 2.9,
    sector: 'HealthTech AI', hq: 'Cambridge, MA',
    isp7_new: true,
    description: 'AI-native, HIPAA-compliant medical search platform enabling physicians to access evidence-based, citation-backed clinical answers in real time. Built on licensed full-text content from NEJM and JAMA. ICONIQ invested via secondary.',
    developments: ['Announced financing round (October 2025)', 'Partnership with AAFP for flagship publications access', 'Launched HIPAA-secure Dialer for physicians (December 2025)'],
  },
  {
    company: 'Oura', date: '2025-09-24', status: 'Private',
    realized: false, fund_pct: 2.8, invested_m: 161.4, fmv_m: 161.4,
    total_value_m: 161.4, gross_moic: 1.0, net_moic: 0.9,
    sector: 'Consumer Health', hq: 'San Francisco, CA',
    isp7_new: true,
    description: 'Leading consumer health company known for its smart ring. Offers continuous biometric tracking across sleep, activity, and recovery. Over 5.5 million members globally. ICONIQ invested in Series E.',
    developments: ['Announced financing round (October 2025)', 'Partnership with American Express as featured benefit for Platinum Card Members'],
  },
  {
    company: 'Outtake', date: '2025-11-07', status: 'Private',
    realized: false, fund_pct: 0.6, invested_m: 33.4, fmv_m: 33.4,
    total_value_m: 33.4, gross_moic: 1.0, net_moic: 0.9,
    sector: 'Cybersecurity AI', hq: 'New York, NY',
    isp7_new: true,
    description: 'AI-powered digital trust and cybersecurity platform automating impersonation detection, open-source intelligence, and digital risk protection across social media, domains, email, and the dark web. ICONIQ led Series B.',
    developments: [],
  },
  {
    company: 'Pepper', date: '2024-04-30', status: 'Private',
    realized: false, fund_pct: 0.5, invested_m: 30.4, fmv_m: 37.3,
    total_value_m: 37.3, gross_moic: 1.2, net_moic: 1.1,
    sector: 'E-commerce / B2B', hq: null,
    description: 'E-commerce platform purpose-built for foodservice distributors to digitize and scale their sales operations.',
    developments: ['Launched Pepper Endless Aisle dropshipping program (July 2025)', 'Acquired Kimelo for AI and vertical-specific capabilities (August 2025)', 'Follow-on of $10.4M in 2H\'25'],
  },
  {
    company: 'Pigment', date: '2023-05-26', status: 'Private',
    realized: false, fund_pct: 3.1, invested_m: 177.1, fmv_m: 304.5,
    total_value_m: 304.5, gross_moic: 1.7, net_moic: 1.5,
    sector: 'FP&A / Business Planning', hq: 'Paris, France',
    description: 'AI-powered business planning and FP&A platform replacing legacy tools like Anaplan. Strong traction in enterprise finance and operations.',
    developments: ['Introduced to 5 ICONIQ portfolio companies + 2 network companies, generating $1.5M in new ARR'],
  },
  {
    company: 'Pontera', date: '2023-11-07', status: 'Private',
    realized: false, fund_pct: 0.8, invested_m: 45.5, fmv_m: 42.9,
    total_value_m: 42.9, gross_moic: 0.9, net_moic: 0.8,
    sector: 'WealthTech', hq: null,
    description: 'Platform enabling financial advisors to manage held-away retirement accounts (401k, IRA) directly from their RIA platforms.',
    developments: [],
  },
  {
    company: 'Project Oasis', date: '2025-09-10', status: 'Private',
    realized: false, fund_pct: 1.9, invested_m: 110.0, fmv_m: 120.2,
    total_value_m: 120.2, gross_moic: 1.1, net_moic: 1.0,
    sector: 'Undisclosed', hq: null,
    description: 'Undisclosed company (operating under codename). Details not publicly available.',
    developments: [],
  },
  {
    company: 'Prompt', date: '2024-09-30', status: 'Private',
    realized: false, fund_pct: 2.7, invested_m: 154.1, fmv_m: 154.4,
    total_value_m: 154.4, gross_moic: 1.0, net_moic: 0.9,
    sector: 'HealthTech / PT', hq: null,
    description: 'Practice management and patient engagement platform for physical therapy and rehabilitation clinics.',
    developments: ['Integrated Prompt Engage (formerly PT Wired) into unified platform (November 2025)', 'Partnership with FYZICAL Therapy & Balance Centers (July 2025)'],
  },
  {
    company: 'Quince', date: '2025-03-14', status: 'Private',
    realized: false, fund_pct: 2.0, invested_m: 117.6, fmv_m: 233.5,
    total_value_m: 233.5, gross_moic: 2.0, net_moic: 1.7,
    sector: 'E-commerce / Apparel', hq: null,
    description: 'E-commerce platform for premium apparel and lifestyle goods, operating a factory-direct model that delivers luxury quality at lower price points.',
    developments: ['Announced Series D financing (July 2025)', 'Launched expanded Home category (August 2025)', 'Follow-on of $2.5M in 2H\'25'],
  },
  {
    company: 'Rain', date: '2025-12-16', status: 'Private',
    realized: false, fund_pct: 1.7, invested_m: 100.0, fmv_m: 100.0,
    total_value_m: 100.0, gross_moic: 1.0, net_moic: 0.9,
    sector: 'Fintech / Stablecoins', hq: 'New York, NY',
    isp7_new: true,
    description: 'Stablecoin-powered payments infrastructure platform enabling FinTechs, neobanks, and global enterprises to issue cards and settle transactions globally. Visa Principal Member. ICONIQ invested in Series C.',
    developments: ['Announced Series C financing (January 2026)'],
  },
  {
    company: 'Ramp', date: '2025-07-28', status: 'Private',
    realized: false, fund_pct: 2.3, invested_m: 134.0, fmv_m: 185.5,
    total_value_m: 185.5, gross_moic: 1.4, net_moic: 1.2,
    sector: 'Fintech / Finance Automation', hq: 'New York, NY',
    isp7_new: true,
    description: 'AI-powered finance automation platform for corporate cards, expense management, bill pay, and procurement. Nearly 40,000 customers. $1.0B ARR as of September 2025. Total FMV across ICONIQ funds: $833M.',
    developments: ['Named to Forbes Cloud 100', 'Announced Series E-2 (July 2025), additional financing (November 2025)', 'Reached $1.0B ARR (September 2025)', 'Launched AI agents for controllers (July 2025) and AP agents (October 2025)'],
  },
  {
    company: 'Restaurant365', date: '2024-04-26', status: 'Private',
    realized: false, fund_pct: 1.3, invested_m: 73.8, fmv_m: 73.8,
    total_value_m: 73.8, gross_moic: 1.0, net_moic: 0.9,
    sector: 'Restaurant Tech', hq: null,
    description: 'All-in-one restaurant management platform covering accounting, operations, scheduling, and inventory for multi-unit restaurant operators.',
    developments: [],
  },
  {
    company: 'Revolut', date: '2025-11-12', status: 'Private',
    realized: false, fund_pct: 0.7, invested_m: 40.0, fmv_m: 40.0,
    total_value_m: 40.0, gross_moic: 1.0, net_moic: 0.9,
    sector: 'Neobanking / Fintech', hq: 'London, UK',
    isp7_new: true,
    description: 'Global financial super-app offering retail banking, investing, payments, and business services across 150+ markets. ICONIQ invested via secondary, attracted by topline metrics and product-led global expansion.',
    developments: ['Announced financing round (November 2025)'],
  },
  {
    company: 'Rillet', date: '2025-08-04', status: 'Private',
    realized: false, fund_pct: 0.4, invested_m: 22.0, fmv_m: 22.0,
    total_value_m: 22.0, gross_moic: 1.0, net_moic: 0.9,
    sector: 'Finance AI / ERP', hq: 'New York, NY',
    isp7_new: true,
    description: 'AI-native general ledger and next-generation ERP platform for modern finance teams. Automates core accounting processes. ICONIQ co-led Series B.',
    developments: ['Announced Series B (August 2025)', 'Partnerships with Attivo and Consero Global for AI-native finance'],
  },
  {
    company: 'Sierra', date: '2024-10-24', status: 'Private',
    realized: false, fund_pct: 0.6, invested_m: 35.0, fmv_m: 60.4,
    total_value_m: 60.4, gross_moic: 1.7, net_moic: 1.5,
    sector: 'AI / Customer Experience', hq: 'San Francisco, CA',
    isp7_new: true,
    description: 'Conversational AI platform purpose-built to transform enterprise customer support. $100M ARR as of November 2025 — only 21 months after launching in February 2024.',
    developments: ['Named to Forbes Cloud 100', 'Reached $100M ARR (November 2025) — launched February 2024', 'Launched Agent OS 2.0 with persistent memory and complex enterprise system execution (December 2025)', 'Follow-on of $10M in 2H\'25'],
  },
  {
    company: 'ST Labs', date: '2025-08-29', status: 'Private',
    realized: false, fund_pct: 0.5, invested_m: 27.0, fmv_m: 43.1,
    total_value_m: 43.1, gross_moic: 1.6, net_moic: 1.4,
    sector: 'IT Management AI', hq: 'New York, NY',
    isp7_new: true,
    description: 'AI-native IT service management platform reimagining ITSM workflows for modern enterprises. Founded by Amit Agarwal, former President of Datadog and ICONIQ General Partner. ICONIQ co-led seed.',
    developments: [],
  },
  {
    company: 'Stripe', date: '2025-12-18', status: 'Private',
    realized: false, fund_pct: 0.9, invested_m: 50.0, fmv_m: 50.0,
    total_value_m: 50.0, gross_moic: 1.0, net_moic: 0.9,
    sector: 'Fintech / Payments', hq: 'San Francisco, CA & Dublin, Ireland',
    isp7_new: true,
    description: 'Leading global payments and financial infrastructure company. Developer-friendly, API-driven stack powering millions of businesses. ICONIQ invested via targeted secondary transaction.',
    developments: [],
  },
  {
    company: 'Swap', date: '2025-01-03', status: 'Private',
    realized: false, fund_pct: 1.1, invested_m: 65.0, fmv_m: 119.8,
    total_value_m: 119.8, gross_moic: 1.8, net_moic: 1.6,
    sector: 'E-commerce Infrastructure', hq: null,
    description: 'All-in-one e-commerce operating system handling shipping, returns, tracking, and international expansion for direct-to-consumer brands.',
    developments: ['Launched Agentic Commerce Platform with AI Agent for Demand Planning (September 2025)', 'Follow-on of $35M in 2H\'25'],
  },
  {
    company: 'Tennr', date: '2025-06-16', status: 'Private',
    realized: false, fund_pct: 0.2, invested_m: 14.1, fmv_m: 14.1,
    total_value_m: 14.1, gross_moic: 1.0, net_moic: 0.9,
    sector: 'HealthTech AI', hq: null,
    description: 'AI-powered document automation platform for healthcare, enabling specialty providers to automate referral processing, prior auth, and administrative workflows.',
    developments: ['Partnership with KabaFusion Partners for AI in home infusion care'],
  },
  {
    company: 'Tiny Fish', date: '2025-05-14', status: 'Private',
    realized: false, fund_pct: 0.4, invested_m: 25.0, fmv_m: 25.0,
    total_value_m: 25.0, gross_moic: 1.0, net_moic: 0.9,
    sector: 'Enterprise AI / Browser', hq: null,
    description: 'AI-native enterprise browser enabling secure, auditable web access for enterprise employees. Built for teams that need governed access to web-based tools and AI applications.',
    developments: ['Announced Series A (August 2025)', 'Launched Mino for enterprise-scale web access (December 2025)'],
  },
  {
    company: 'UnifyApps', date: '2024-09-12', status: 'Private',
    realized: false, fund_pct: 0.3, invested_m: 17.4, fmv_m: 36.5,
    total_value_m: 36.5, gross_moic: 2.1, net_moic: 1.8,
    sector: 'Enterprise Integration', hq: null,
    description: 'Low-code enterprise integration and automation platform enabling companies to connect and orchestrate their software stack without heavy engineering investment.',
    developments: ['Announced Series B (October 2025)'],
  },
  {
    company: 'Virtru', date: '2025-06-20', status: 'Private',
    realized: false, fund_pct: 0.8, invested_m: 46.0, fmv_m: 46.2,
    total_value_m: 46.2, gross_moic: 1.0, net_moic: 0.9,
    sector: 'Cybersecurity / Encryption', hq: null,
    description: 'Data-centric security and encryption platform enabling organizations to share sensitive data across email, files, and cloud applications while maintaining control.',
    developments: ['New Senior Solutions Architect: Don Yeske (former Navy CTO and DHS Cyber Leader, September 2025)', 'Follow-on of $5.3M in 2H\'25'],
  },
  {
    company: 'Whirl AI', date: '2025-06-18', status: 'Private',
    realized: false, fund_pct: 0.1, invested_m: 7.5, fmv_m: 7.5,
    total_value_m: 7.5, gross_moic: 1.0, net_moic: 0.9,
    sector: 'AI (TBD)', hq: null,
    description: 'Early-stage AI company. Details not yet publicly available.',
    developments: [],
  },
  {
    company: 'Writer', date: '2023-08-16', status: 'Private',
    realized: false, fund_pct: 1.2, invested_m: 70.0, fmv_m: 156.6,
    total_value_m: 156.6, gross_moic: 2.2, net_moic: 2.0,
    sector: 'Enterprise AI', hq: 'San Francisco, CA',
    description: 'Full-stack enterprise AI from custom models (Palmyra) to workflow automation. Strong traction in pharma, financial services, and retail. Competing with Microsoft Copilot.',
    developments: ['Announced launch of Action Agent — autonomous AI super agent for enterprise users'],
  },
]

// ─── ISP VII Recent New Investments (2H 2025) ───────────────────────────────
export const ISP7_RECENT = ISP7_PORTFOLIO
  .filter(p => p.isp7_new)
  .map(p => p.company)

// ─── Fund Performance (All ISP Funds) ───────────────────────────────────────
export const FUND_STATS = [
  { fund: 'ISP I',   committed_m: 509.0,  invested_m: 516.1,  total_value_m: 1615.4, gross_moic: 3.1, net_moic: 2.6, net_irr: '20.0%', dpi: '2.6x' },
  { fund: 'ISP II',  committed_m: 1024.3, invested_m: 1081.7, total_value_m: 8543.6, gross_moic: 7.9, net_moic: 6.0, net_irr: '32.6%', dpi: '4.2x' },
  { fund: 'ISP III', committed_m: 1326.0, invested_m: 1458.5, total_value_m: 9691.1, gross_moic: 6.6, net_moic: 5.3, net_irr: '49.9%', dpi: '4.7x' },
  { fund: 'ISP IV',  committed_m: 1836.0, invested_m: 1811.7, total_value_m: 3968.2, gross_moic: 2.2, net_moic: 1.8, net_irr: '12.8%', dpi: '0.8x' },
  { fund: 'ISP V',   committed_m: 2629.0, invested_m: 2963.2, total_value_m: 3527.6, gross_moic: 1.2, net_moic: 1.1, net_irr: '1.5%',  dpi: '0.0x' },
  { fund: 'ISP VI',  committed_m: 4061.8, invested_m: 3782.0, total_value_m: 5212.5, gross_moic: 1.4, net_moic: 1.2, net_irr: '4.7%',  dpi: '0.0x' },
  { fund: 'ISP VII', committed_m: 5750.0, invested_m: 4674.4, total_value_m: 7022.9, gross_moic: 1.5, net_moic: 1.3, net_irr: '25.4%', dpi: '0.0x' },
]

export const ISP7_STATS = {
  lp_commitment: 5593281667,
  contributed_m: 4641.0,
  distributions_m: 0,
  nav_m: 6063.9,
  net_moic: 1.3,
  net_irr: '25.4%',
  pct_invested: 81.3,
  active_cos: 53,
  realized_cos: 1,
}

export const PORTFOLIO_STATS = {
  total_cos: 174,
  portfolio_value_b: 52.1,
  net_value_appreciation_b: 20.2,
  liquidity_events: 51,
  lp_distributions_b: 17.0,
  realized_net_moic: '4.0x',
  fy2025_invested_b: 5.1,
  fy2025_irr: '2.4x',
  portfolio_topline_growth_2025: '71%',
}

// ─── Investment Thesis Signals (from ISP VII LP Letter) ─────────────────────
export const INVESTMENT_THESIS = {
  favors: [
    'Deeply embedded workflows and strong integration ecosystems',
    'Proprietary datasets as defensible moats',
    'Trusted security postures in regulated industries',
    'Durable revenue reacceleration (not just margin expansion)',
    'AI as a compounding force, not a vulnerability',
    'TAM expansion potential through AI-native capabilities',
    'Novel pricing models capturing AI value creation',
    'Management teams that can adapt quickly to AI capabilities',
    'Enterprise-focused applications with strong retention',
    'Data infrastructure companies insulated from AI disruption',
  ],
  avoids: [
    'Business models with limited proprietary data',
    'Easily replicable workflow products',
    'Weak integrations or ecosystems',
    'Scale without a credible path to re-acceleration',
    'Consumer AI without a clear enterprise monetization path',
  ],
}

export const THESIS_SYSTEM_PROMPT = `You are an AI assistant for an ICONIQ Growth associate. ICONIQ is a growth equity firm.

ICONIQ's investment thesis — what they favor:
${INVESTMENT_THESIS.favors.map((s, i) => `${i + 1}. ${s}`).join('\n')}

What ICONIQ avoids:
${INVESTMENT_THESIS.avoids.map(s => `- ${s}`).join('\n')}

ICONIQ's highest-conviction recent investments (ISP VII 2H'25): ${ISP7_RECENT.join(', ')}.`

// ─── Synergy matching helper ─────────────────────────────────────────────────
export function getSynergyMatches(synergyList) {
  if (!synergyList) return []
  return synergyList.map(name => ({
    name,
    inPortfolio: ICONIQ_PORTFOLIO.some(p => p.toLowerCase() === name.toLowerCase()),
    isp7: ISP7_RECENT.some(p => p.toLowerCase() === name.toLowerCase()),
    isp7Data: ISP7_PORTFOLIO.find(p => p.company.toLowerCase() === name.toLowerCase()),
  }))
}
